= 3rd-Party Builds

This repository is used to build and publish _RELEASE_, _RC_ and _SNAPSHOT_ versions of third-party libraries.

== Libraries

The artifacts are published to a _Google Arifact Repository_ and can be fetched via https://europe-north1-maven.pkg.dev/gcp-uweeisele-dev/third-party-maven-releases and https://europe-north1-maven.pkg.dev/gcp-uweeisele-dev/third-party-maven-snapshots.

.Add the following snippet to your `gradle.build` file
[source,java]
----
repositories {
    maven {
        url 'https://europe-north1-maven.pkg.dev/gcp-uweeisele-dev/third-party-maven-releases'
        mavenContent {
            releasesOnly()
        }
    }
    maven {
        url 'https://europe-north1-maven.pkg.dev/gcp-uweeisele-dev/third-party-maven-snapshots'
        mavenContent {
            snapshotsOnly()
        }
    }
}
----

.Add the following snippet to your `pom.xml` file
[source,xml]
----
<repositories>
  <repository>
    <id>third-party-releases</id>
    <url>https://europe-north1-maven.pkg.dev/gcp-uweeisele-dev/third-party-maven-releases</url>
    <releases>
      <enabled>true</enabled>
    </releases>
    <snapshots>
      <enabled>false</enabled>
    </snapshots>
  </repository>
  <repository>
    <id>third-party-snapshots</id>
    <url>https://europe-north1-maven.pkg.dev/gcp-uweeisele-dev/third-party-maven-snapshots</url>
    <releases>
      <enabled>false</enabled>
    </releases>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </repository>
</repositories>
----

=== Apache Kafka

This repository is used to build and publish _RELEASE_, _RC_ and _SNAPSHOT_ versions of link:https://github.com/apache/kafka.git[Apache Kafka] Wednesday and Saturday.

At the moment versions for Apache Kafka _3.8.0_ and _3.9-SNAPSHOT_ are build and published.

.To install a Release version of Apache's Kafka Streams 3.8.0 with Gradle
[source,groovy]
----
compile group: 'org.apache.kafka', name: 'kafka-streams', version: '3.8.0'
----

.To install a Snapshot version of Apache's Kafka Streams 3.9.0 with Gradle
[source,groovy]
----
compile group: 'org.apache.kafka', name: 'kafka-streams', version: '3.9.0-SNAPSHOT'
----

== Development

.Print Gradle settings
[source,bash]
----
gcloud artifacts print-settings gradle --project gcp-uweeisele-dev --location europe-north1 --repository third-party-maven-releases
----

.Print Maven settings
[source,bash]
----
gcloud artifacts print-settings mvn --project gcp-uweeisele-dev --location europe-north1 --repository third-party-maven-releases
----

.Build locally
[source,bash]
----
BUILD=3.8.0 apache/kafka/build.sh
----

.Build locally in Docker
[source,bash]
----
BUILD=3.8.0 docker/run_in_docker.sh apache/kafka/build.sh
----