= Kafka Builds

This repository is used to build and publish _SNAPSHOT_ and _RC_ versions of link:https://github.com/apache/kafka.git[Apache Kafka], link:https://github.com/confluentinc/kafka.git[Confluent Kafka] and related tools Wednesday and Saturday.
The following repositories are considered: 
 
 * link:https://github.com/apache/kafka.git[]
 * link:https://github.com/confluentinc/kafka.git[]
 * link:https://github.com/confluentinc/common.git[]
 * link:https://github.com/confluentinc/rest-utils.git[]
 * link:https://github.com/confluentinc/schema-registry.git[]
 * link:https://github.com/confluentinc/kafka-rest.git[]
 * link:https://github.com/confluentinc/ksql.git[]

At the moment versions for Apache Kafka _3.1_ and _3.2_ and Confluent _7.1_ are build and published.

The artifacts have `-SNAPSHOT` as version suffix.

.To install a Snapshot version of Apache's Kafka Streams 3.1.0 with Gradle
[source,groovy]
----
compile group: 'org.apache.kafka', name: 'kafka-streams', version: '3.1.0-SNAPSHOT'
----

.To install a Snapshot version of Confluent's Kafka Streams 7.1.0 with Gradle
[source,groovy]
----
compile group: 'org.apache.kafka', name: 'kafka-streams', version: '7.1.0-ccs-SNAPSHOT'
----

.To install a Snapshot version of Confluent's Kafka Avro Serializer 7.1.0 with Gradle
[source,groovy]
----
compile group: 'io.confluent', name: 'kafka-avro-serializer', version: '7.1.0-SNAPSHOT'
----

The artifacts are published to a _Google Arifact Repository_ and can be fetched via https://europe-west3-maven.pkg.dev/gcp-uweeisele-dev/kafka-snapshots for Apache Kafka and https://europe-west3-maven.pkg.dev/gcp-uweeisele-dev/confluent-snapshots for Confluent.


.Add the following snippet to your `gradle.build` file
[source,java]
----
repositories {
    maven {
        url 'https://europe-west3-maven.pkg.dev/gcp-uweeisele-dev/kafka-snapshots'
        mavenContent {
            snapshotsOnly()
        }
    }
    maven {
        url 'https://europe-west3-maven.pkg.dev/gcp-uweeisele-dev/confluent-snapshots'
        mavenContent {
            snapshotsOnly()
        }
    }
}
----

.Add the following snippet to yout `pom.xml` file
[source,xml]
----
<repositories>
  <repository>
    <id>kafka-snapshots</id>
    <url>https://europe-west3-maven.pkg.dev/gcp-uweeisele-dev/kafka-snapshots</url>
    <releases>
      <enabled>false</enabled>
    </releases>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </repository>
  <repository>
    <id>confluent-snapshots</id>
    <url>https://europe-west3-maven.pkg.dev/gcp-uweeisele-dev/confluent-snapshots</url>
    <releases>
      <enabled>false</enabled>
    </releases>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </repository>
</repositories>
----
