ARG ALMA_VERSION
FROM docker.io/almalinux/9-minimal:${ALMA_VERSION}
LABEL maintainer="code@uweeisele.eu"

ENV LANG="C.UTF-8"

ARG ZULU_OPENJDK_RELEASE ZULU_OPENJDK_VERSION
ENV ZULU_OPENJDK="zulu${ZULU_OPENJDK_RELEASE}-jdk-headless-${ZULU_OPENJDK_VERSION}"
LABEL openjdk=${ZULU_OPENJDK}

ENV JAVA_HOME="/usr/lib/jvm/zulu${ZULU_OPENJDK_RELEASE}"

RUN rpm --import https://www.azul.com/files/0xB1998361219BD9C9.txt \
    && rpm --install https://cdn.azul.com/zulu/bin/zulu-repo-1.0.0-1.noarch.rpm \
    && microdnf install ${ZULU_OPENJDK} hostname findutils tar gzip unzip git shadow-utils \
         --setopt=install_weak_deps=0 --nodocs -y \
    && useradd --no-log-init --create-home --shell /bin/bash appuser \
    && microdnf remove -y shadow-utils \
    && microdnf clean all \
    && rm -rf /tmp/* && rm -rf /var/lib/rpm  && rm -rf /var/cache/yum && rm -rf /var/lib/dnf

USER appuser
WORKDIR /home/appuser